#!/usr/bin/env python
############################################################################
#
# wxgui.py
#
# Copyright 2004 Donour Sizemore (donour@uchicago.edu)
# Copyright 2009 Secons Ltd. (www.obdtester.com)
#
# This file is part of pyOBD.
#
# pyOBD is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# pyOBD is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with pyOBD; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
############################################################################

import ConfigParser  # safe application configuration
import os  # os.environ
import platform
import sys
import threading
import time
import webbrowser  # open browser from python
from datetime import datetime

import serial
#import wxversion
#wxversion.select("2.6")
import wx
from wx.lib.mixins.listctrl import ListCtrlAutoWidthMixin

import obd_io  # OBD2 funcs
from debugEvent import *
from obd2_codes import pcodes, ptest
from obd_utils import scanBluetooth, scanSerial

ID_ABOUT = 101
ID_EXIT = 110
ID_CONFIG = 500
ID_CLEAR = 501
ID_GETC = 502
ID_RESET = 503
ID_LOOK = 504
ALL_ON = 505
ALL_OFF = 506

ID_DISCONNECT = 507
ID_HELP_ABOUT = 508
ID_HELP_VISIT = 509
ID_HELP_ORDER = 510

# Define notification event for sensor result window
EVT_RESULT_ID = 1000


def EVT_RESULT(win, func, id):
    """Define Result Event."""
    win.Connect(-1, -1, id, func)

#event pro akutalizaci Trace tabu


class ResultEvent(wx.PyEvent):
   """Simple event to carry arbitrary result data."""

   def __init__(self, data):
       """Init Result Event."""
       wx.PyEvent.__init__(self)
       self.SetEventType(EVT_RESULT_ID)
       self.data = data

#event pro aktualizaci DTC tabu
EVT_DTC_ID = 1001


class DTCEvent(wx.PyEvent):
   """Simple event to carry arbitrary result data."""

   def __init__(self, data):
       """Init Result Event."""
       wx.PyEvent.__init__(self)
       self.SetEventType(EVT_DTC_ID)
       self.data = data

#event pro aktualizaci status tabu
EVT_STATUS_ID = 1002


class StatusEvent(wx.PyEvent):
   """Simple event to carry arbitrary result data."""

   def __init__(self, data):
       """Init Result Event."""
       wx.PyEvent.__init__(self)
       self.SetEventType(EVT_STATUS_ID)
       self.data = data

#event pro aktualizaci tests tabu
EVT_TESTS_ID = 1003


class TestEvent(wx.PyEvent):
   """Simple event to carry arbitrary result data."""

   def __init__(self, data):
       """Init Result Event."""
       wx.PyEvent.__init__(self)
       self.SetEventType(EVT_TESTS_ID)
       self.data = data

EVT_MONDATA_ID = 1004


class MonitorDataEvent(wx.PyEvent):
    """Event that carries a line of monitor data"""

    def __init__(self, data):
        wx.PyEvent.__init__(self)
        self.SetEventType(EVT_MONDATA_ID)
        self.data = data


class MyApp(wx.App):
    TAB_STATUS = 0
    TAB_TESTS = 1
    TAB_SENSORS = 2
    TAB_DTC = 3
    TAB_MONITOR = 4

    # A listctrl which auto-resizes the column boxes to fill
    class MyListCtrl(wx.ListCtrl, ListCtrlAutoWidthMixin):

        def __init__(self, parent, id, pos=wx.DefaultPosition,
                     size=wx.DefaultSize, style=0):
            wx.ListCtrl.__init__(self, parent, id, pos, size, style)
            ListCtrlAutoWidthMixin.__init__(self)

    class sensorProducer(threading.Thread):

        def __init__(self, _notify_window, portName, SERTIMEOUT, RECONNATTEMPTS, _nb):
            from Queue import Queue
            self.portName = portName
            self.RECONNATTEMPTS = RECONNATTEMPTS
            self.SERTIMEOUT = SERTIMEOUT
            self.port = None
            self._notify_window = _notify_window
            self._nb = _nb
            threading.Thread.__init__(self)

        def initCommunication(self):
            self.port = obd_io.OBDPort(
                self.portName, self._notify_window, self.SERTIMEOUT, self.RECONNATTEMPTS)

            if self.port.State == 0:  # Cant open serial port
                self.port.close()
                return self.port.Error

            self.active = []
            self.supp = '1'  # PID 00 always supported
            self.supp += self.port.sensor(0x00)[1]  # read supported PIDS

            if self.supp[-1:] == '1':
                self.supp += self.port.sensor(0x20)[1]
            if self.supp[-1:] == '1':
                self.supp += self.port.sensor(0x40)[1]
            if self.supp[-1:] == '1':
                self.supp += self.port.sensor(0x60)[1]
            if self.supp[-1:] == '1':
                self.supp += self.port.sensor(0x80)[1]

            wx.PostEvent(self._notify_window, ResultEvent([0, 0, "X"]))
            wx.PostEvent(self._notify_window, DebugEvent(
                [1, "Communication initialized..."]))

            for i in range(0, len(self.supp)):
                has_sensor = obd_io.obd_sensors.get_sensor(i) != None
                # put X in column if PID is supported
                if self.supp[i] == "1" and has_sensor:
                    self.active.append(1)
                    wx.PostEvent(self._notify_window, ResultEvent([i, 0, "X"]))
                else:
                    self.active.append(0)
                    wx.PostEvent(self._notify_window, ResultEvent([i, 0, ""]))
            return "OK"

        def run(self):
            wx.PostEvent(self._notify_window, StatusEvent(
                [0, 1, "Connecting...."]))
            status = self.initCommunication()
            if self.port.State == 0:  # cant connect, exit thread
              self.stop()
              # signal apl, that communication was disconnected
              wx.PostEvent(self._notify_window, StatusEvent([-1]))
              wx.PostEvent(self._notify_window, StatusEvent(
                  [0, 1, "Could not connect: %s" % status]))
              return None

            # tell the application that we're connected
            wx.PostEvent(self._notify_window, StatusEvent([1]))
            wx.PostEvent(self._notify_window, StatusEvent([0, 1, "Connected"]))
            wx.PostEvent(self._notify_window, StatusEvent(
                [2, 1, self.port.ELMver]))
            prevtab = -1
            curtab = -1
            while self._notify_window.ThreadControl != 666:
                prevtab = curtab
                curtab = self._nb.GetSelection()
                if curtab == MyApp.TAB_STATUS:  # show status tab
                    pass
                elif curtab == MyApp.TAB_TESTS:  # show tests tab
                    res = self.port.get_tests_MIL()
                    for i in range(0, len(res)):
                        wx.PostEvent(self._notify_window,
                                     TestEvent([i, 1, res[i]]))

                elif curtab == MyApp.TAB_SENSORS:  # show sensor tab
                    for i in range(3, len(self.active)):
                        if self.active[i]:
                            s = self.port.sensor(i)
                            if s != None:
                                # value
                                disp = "%s" % s[1]

                                # units
                                if s[2] != '':
                                    disp += " %s" % s[2]

                                wx.PostEvent(self._notify_window,
                                             ResultEvent([i, 2, disp]))

                        # exit
                        if self._notify_window.ThreadControl == 666:
                            break
                elif curtab == MyApp.TAB_DTC:  # show DTC tab
                    if self._notify_window.ThreadControl == 1:  # clear DTC
                        self.port.clear_dtc()

                        # before reset ThreadControl we must check if main thread
                        # did not want us to finish
                        if self._notify_window.ThreadControl == 666:
                            break

                        self._notify_window.ThreadControl = 0
                        prevtab = -1  # to reread DTC
                    if self._notify_window.ThreadControl == 2:  # reread DTC
                        prevtab = -1

                        if self._notify_window.ThreadControl == 666:
                            break

                        self._notify_window.ThreadControl = 0

                    # Update DTC List Again
                    if prevtab != 3:
                        wx.PostEvent(self._notify_window,
                                     DTCEvent(0))  # clear list
                        DTCCodes = self.port.get_dtc()
                        if len(DTCCodes) == 0:
                            wx.PostEvent(self._notify_window, DTCEvent(
                                ["", "", "No DTC codes (codes cleared)"]))

                        for i in range(0, len(DTCCodes)):
                            translated_code = "Unknown"
                            if DTCCodes[i][1] in pcodes:
                                translated_code = pcodes[DTCCodes[i][1]]

                            wx.PostEvent(self._notify_window, DTCEvent(
                                [DTCCodes[i][1], DTCCodes[i][0], translated_code]))
                elif curtab == MyApp.TAB_MONITOR:
                    # Enter monitor mode (while 1)
                    if self._notify_window.ThreadControl == 1:
                        self.port.enable_monitor(True)

                        # Once entered, we loop here.
                        try:
                            while curtab == MyApp.TAB_MONITOR and self._notify_window.ThreadControl == 1:
                                curtab = self._nb.GetSelection()

                                lines = self.port.recv_data()
                                for line in lines:
                                    if line == 'BUFFER FULL':
                                        # If you poke it, it'll keep dumping
                                        # data
                                        self.port.send_raw('\r')
                                        nlines = self.port.recv_data()
                                        lines.extend(nlines)
                                        continue

                                    line.strip()
                                    if line == '':
                                        # ignore blank lines
                                        continue

                                    if line[0] == '>':
                                        # strip chevron
                                        line = line[1:]

                                    # HACK: Make sure the lines are proper length (some may be cut off)
                                    # [3 char id] b1 b2 ... b8 [1 trailing whitespace]
                                    if len(line) != 4 + 8 * 3:
                                        continue

                                    wx.PostEvent(self._notify_window, MonitorDataEvent(
                                        [datetime.now().strftime("%H:%M:%S.%f"), line]))
                        except IOError as e:
                            print("Disconnected? Disabling monitor mode (ex %s)" % e)
                            pass

                        # disable monitor mode
                        self.port.enable_monitor(False)
                else:
                    pass
            self.stop()

        def off(self, id):
            if id >= 0 and id < len(self.active):
                self.active[id] = 0
            else:
                debug("Invalid sensor id")

        def on(self, id):
            if id >= 0 and id < len(self.active):
                self.active[id] = 1
            else:
                debug("Invalid sensor id")

        def all_off(self):
            for i in range(0, len(self.active)):
                self.off(i)

        def all_on(self):
            for i in range(0, len(self.active)):
                self.off(i)

        def stop(self):
            # if stop is called before any connection port is not defined (and
            # not connected )
            if self.port != None:
              self.port.close()
            wx.PostEvent(self._notify_window,
                         StatusEvent([0, 1, "Disconnected"]))
            wx.PostEvent(self._notify_window, StatusEvent([2, 1, "----"]))

  #class producer end

    def sensor_control_on(self):  # after connection enable few buttons
        self.settingmenu.Enable(ID_CONFIG, False)
        self.settingmenu.Enable(ID_RESET, False)
        self.settingmenu.Enable(ID_DISCONNECT, True)
        self.dtcmenu.Enable(ID_GETC, True)
        self.dtcmenu.Enable(ID_CLEAR, True)
        self.GetDTCButton.Enable(True)
        self.ClearDTCButton.Enable(True)
        self.BeginMonitorButton.Enable(True)
        self.EndMonitorButton.Enable(True)

        def sensor_toggle(e):
            sel = e.m_itemIndex
            state = self.senprod.active[sel]
            print sel, state
            if state == 0:
                self.senprod.on(sel)
                self.sensors.SetStringItem(sel, 1, "1")
            elif state == 1:
                self.senprod.off(sel)
                self.sensors.SetStringItem(sel, 1, "0")
            else:
                debug("Incorrect sensor state")

        self.sensors.Bind(wx.EVT_LIST_ITEM_ACTIVATED,
                          sensor_toggle, id=self.sensor_id)

    def sensor_control_off(self):  # after disconnect disable fer buttons
        self.dtcmenu.Enable(ID_GETC, False)
        self.dtcmenu.Enable(ID_CLEAR, False)
        self.settingmenu.Enable(ID_DISCONNECT, False)
        self.settingmenu.Enable(ID_CONFIG, True)
        self.settingmenu.Enable(ID_RESET, True)
        self.GetDTCButton.Enable(False)
        self.ClearDTCButton.Enable(False)
        self.BeginMonitorButton.Enable(False)
        self.EndMonitorButton.Enable(False)

    def build_sensor_page(self):
        tID = wx.NewId()
        self.sensor_id = tID
        panel = wx.Panel(self.nb, -1)
        sizer = wx.BoxSizer(wx.VERTICAL)

        self.sensor_map = {}
        self.sensors = self.MyListCtrl(panel, tID,
                                       style=wx.LC_REPORT |
                                       wx.SUNKEN_BORDER |
                                       wx.LC_HRULES |
                                       wx.LC_SINGLE_SEL)
        sizer.Add(self.sensors, 1, wx.ALL | wx.EXPAND, 3)

        self.sensors.InsertColumn(0, "Supported", width=70)
        self.sensors.InsertColumn(
            1, "Sensor", format=wx.LIST_FORMAT_RIGHT, width=250)
        self.sensors.InsertColumn(2, "Value")
        for i in range(0, len(obd_io.obd_sensors.SENSORS)):
            s = obd_io.obd_sensors.SENSORS[i].name
            id = obd_io.obd_sensors.SENSORS[i].id
            self.sensor_map[id] = i

            self.sensors.InsertStringItem(i, "")
            self.sensors.SetStringItem(i, 1, s)

        panel.SetSizer(sizer)
        self.nb.AddPage(panel, "Sensors")

    def build_DTC_page(self):
        HOFFSET_LIST = 30  # offset from the top of panel (space for buttons)
        tID = wx.NewId()
        self.DTCpanel = wx.Panel(self.nb, -1)
        sizer = wx.BoxSizer(wx.VERTICAL)

        btn_sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.GetDTCButton = wx.Button(self.DTCpanel, -1, "Get DTC")
        self.ClearDTCButton = wx.Button(self.DTCpanel, -1, "Clear DTC")
        btn_sizer.Add(self.GetDTCButton, 0, wx.ALL, 3)
        btn_sizer.Add(self.ClearDTCButton, 0, wx.ALL, 3)
        sizer.Add(btn_sizer, 0, wx.ALL | wx.EXPAND, 3)

        #bind functions to button click action
        self.DTCpanel.Bind(wx.EVT_BUTTON, self.GetDTC, self.GetDTCButton)
        self.DTCpanel.Bind(wx.EVT_BUTTON, self.QueryClear, self.ClearDTCButton)

        self.dtc = self.MyListCtrl(
            self.DTCpanel, tID, style=wx.LC_REPORT | wx.SUNKEN_BORDER | wx.LC_HRULES | wx.LC_SINGLE_SEL)
        sizer.Add(self.dtc, 1, wx.EXPAND, 5)

        self.dtc.InsertColumn(0, "Code", width=100)
        self.dtc.InsertColumn(1, "Status", width=100)
        self.dtc.InsertColumn(2, "Trouble code")

        self.DTCpanel.SetSizer(sizer)
        self.nb.AddPage(self.DTCpanel, "DTC")

    def build_monitor_page(self):
        tID = wx.NewId()
        self.Monitorpanel = wx.Panel(self.nb, -1)
        sizer = wx.BoxSizer(wx.VERTICAL)

        # Maps id -> row
        self._monitor_map = {}

        btn_sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.BeginMonitorButton = wx.Button(
            self.Monitorpanel, -1, "Begin Monitoring")
        self.EndMonitorButton = wx.Button(
            self.Monitorpanel, -1, "End Monitoring")
        self.ClearMonitorButton = wx.Button(self.Monitorpanel, -1, "Clear")
        self.SaveMonitorButton = wx.Button(self.Monitorpanel, -1, "Save As...")
        btn_sizer.Add(self.BeginMonitorButton, 0, wx.ALL, 3)
        btn_sizer.Add(self.EndMonitorButton, 0, wx.ALL, 3)
        btn_sizer.Add(self.ClearMonitorButton, 0, wx.ALL, 3)
        btn_sizer.Add(self.SaveMonitorButton, 0, wx.ALL, 3)
        sizer.Add(btn_sizer, 0, wx.ALL | wx.EXPAND, 3)

        #bind functions to button click action
        self.Monitorpanel.Bind(
            wx.EVT_BUTTON, self.BeginMonitoring, self.BeginMonitorButton)
        self.Monitorpanel.Bind(
            wx.EVT_BUTTON, self.EndMonitoring, self.EndMonitorButton)
        self.Monitorpanel.Bind(
            wx.EVT_BUTTON, self.ClearMonitor, self.ClearMonitorButton)
        self.Monitorpanel.Bind(
            wx.EVT_BUTTON, self.SaveMonitor, self.SaveMonitorButton)

        self.monitor = self.MyListCtrl(self.Monitorpanel, tID,
                                       style=wx.LC_REPORT | wx.SUNKEN_BORDER | wx.LC_HRULES | wx.LC_SINGLE_SEL)

        sizer.Add(self.monitor, 1, wx.EXPAND, 5)

        # Columns
        self.monitor.InsertColumn(0, "Time", width=100)
        self.monitor.InsertColumn(1, "ID")
        self.monitor.InsertColumn(2, "Bytes")

        # Finalization
        self.Monitorpanel.SetSizer(sizer)
        self.nb.AddPage(self.Monitorpanel, "Monitoring")

    def TraceDebug(self, level, msg):
        if self.DEBUGLEVEL <= level:
            self.trace.Append([str(level), msg])

    def OnInit(self):
        self.ThreadControl = 0  # say thread what to do
        self.COMPORT = 0
        self.senprod = None
        self.DEBUGLEVEL = 0  # debug everthing

        tID = wx.NewId()

        #read settings from file
        self.config = ConfigParser.RawConfigParser()

        #print platform.system()
        #print platform.mac_ver()[]

        if "OS" in os.environ.keys():  # running under windows
          self.configfilepath = "pyobd.ini"
        else:
          self.configfilepath = os.environ['HOME'] + '/.pyobdrc'
        if self.config.read(self.configfilepath) == []:
          self.COMPORT = "/dev/ttyACM0"
          self.RECONNATTEMPTS = 5
          self.SERTIMEOUT = 2
          self.FRAMESIZE = (520, 400)
        else:
          self.COMPORT = self.config.get("pyOBD", "COMPORT")
          self.RECONNATTEMPTS = self.config.getint("pyOBD", "RECONNATTEMPTS")
          self.SERTIMEOUT = self.config.getint("pyOBD", "SERTIMEOUT")
          self.FRAMESIZE = (self.config.getint("pyOBD", "WINSIZEX"),
                            self.config.getint("pyOBD", "WINSIZEY"))

        frame = wx.Frame(None, -1, "pyOBD-II")
        self.frame = frame

        EVT_RESULT(self, self.OnResult, EVT_RESULT_ID)
        EVT_RESULT(self, self.OnDebug, EVT_DEBUG_ID)
        EVT_RESULT(self, self.OnDtc, EVT_DTC_ID)
        EVT_RESULT(self, self.OnStatus, EVT_STATUS_ID)
        EVT_RESULT(self, self.OnTests, EVT_TESTS_ID)
        EVT_RESULT(self, self.OnMonitorData, EVT_MONDATA_ID)

        # Main notebook frames
        self.nb = wx.Notebook(frame, -1, style=wx.NB_TOP)

        self.status = self.MyListCtrl(
            self.nb, tID, style=wx.LC_REPORT | wx.SUNKEN_BORDER)
        self.status.InsertColumn(0, "Description", width=200)
        self.status.InsertColumn(1, "Value")
        self.status.Append(["Link State", "Disconnnected"])
        self.status.Append(["Protocol", "---"])
        self.status.Append(["Cable version", "---"])
        self.status.Append(["COM/BT port", self.COMPORT])

        # These pages are dependent on the ordering at the top of this class!
        self.nb.AddPage(self.status, "Status")

        self.OBDTests = self.MyListCtrl(
            self.nb, tID, style=wx.LC_REPORT | wx.SUNKEN_BORDER)
        self.OBDTests.InsertColumn(0, "Description", width=200)
        self.OBDTests.InsertColumn(1, "Value")
        self.nb.AddPage(self.OBDTests, "Tests")

        for i in range(0, len(ptest)):  # fill MODE 1 PID 1 test description
          self.OBDTests.Append([ptest[i], "---"])

        self.build_sensor_page()

        self.build_DTC_page()

        self.build_monitor_page()

        self.trace = self.MyListCtrl(
            self.nb, tID, style=wx.LC_REPORT | wx.SUNKEN_BORDER)
        self.trace.InsertColumn(0, "Level", width=40)
        self.trace.InsertColumn(1, "Message")
        self.nb.AddPage(self.trace, "Trace")
        self.TraceDebug(1, "Application started")

        # Setting up the menu.
        self.filemenu = wx.Menu()
        self.filemenu.Append(ID_EXIT, "E&xit", " Terminate the program")

        self.settingmenu = wx.Menu()
        self.settingmenu.Append(ID_CONFIG, "Con&figure", " Configure pyOBD")
        self.settingmenu.Append(ID_RESET, "&Connect\tF2",
                                " Reopen and connect to device")
        self.settingmenu.Append(
            ID_DISCONNECT, "&Disconnect\tF3", "Close connection to device")

        self.dtcmenu = wx.Menu()
        # tady toto nastavi automaticky tab DTC a provede akci
        self.dtcmenu.Append(ID_GETC, "Get DTCs",   " Get DTC Codes")
        self.dtcmenu.Append(ID_CLEAR, "Clear DTC",  " Clear DTC Codes")
        self.dtcmenu.Append(ID_LOOK, "Code Lookup", " Lookup DTC Codes")

        self.helpmenu = wx.Menu()

        self.helpmenu.Append(
            ID_HELP_ABOUT, "About this program",   " Get DTC Codes")
        self.helpmenu.Append(
            ID_HELP_VISIT, "Visit program homepage", " Lookup DTC Codes")
        self.helpmenu.Append(
            ID_HELP_ORDER, "Order OBD-II cables",  " Clear DTC Codes")

        # Creating the menubar.
        self.menuBar = wx.MenuBar()
        # Adding the "filemenu" to the MenuBar
        self.menuBar.Append(self.filemenu, "&File")
        self.menuBar.Append(self.settingmenu, "&OBD-II")
        self.menuBar.Append(self.dtcmenu, "&Trouble codes")
        self.menuBar.Append(self.helpmenu, "&Help")

        # Adding the MenuBar to the Frame content.
        frame.SetMenuBar(self.menuBar)

        # Create a status bar as well
        self.statusBar = frame.CreateStatusBar()
        self.statusBar.SetStatusText("Disconnected", 0)

        # attach the menu-event ID_EXIT to the
        frame.Bind(wx.EVT_MENU, self.OnExit, id=ID_EXIT)
        frame.Bind(wx.EVT_MENU, self.QueryClear, id=ID_CLEAR)
        frame.Bind(wx.EVT_MENU, self.Configure, id=ID_CONFIG)
        frame.Bind(wx.EVT_MENU, self.OpenPort, id=ID_RESET)
        frame.Bind(wx.EVT_MENU, self.OnDisconnect, id=ID_DISCONNECT)
        frame.Bind(wx.EVT_MENU, self.GetDTC, id=ID_GETC)
        frame.Bind(wx.EVT_MENU, self.CodeLookup, id=ID_LOOK)
        frame.Bind(wx.EVT_MENU, self.OnHelpAbout, id=ID_HELP_ABOUT)
        frame.Bind(wx.EVT_MENU, self.OnHelpVisit, id=ID_HELP_VISIT)
        frame.Bind(wx.EVT_MENU, self.OnHelpOrder, id=ID_HELP_ORDER)
        frame.Bind(wx.EVT_SIZE, self.OnResize)

        # Accelerators
        accel_table = wx.AcceleratorTable(
            [(wx.ACCEL_NORMAL, wx.WXK_F2, ID_RESET), (wx.ACCEL_NORMAL, wx.WXK_F3, ID_DISCONNECT)])
        frame.SetAcceleratorTable(accel_table)

        self.SetTopWindow(frame)

        frame.SetSize((self.FRAMESIZE[0], self.FRAMESIZE[1]))
        frame.Show(True)
        self.sensor_control_off()

        return True

    def OnHelpVisit(self, event):
        webbrowser.open("http://www.obdtester.com/pyobd")

    def OnHelpOrder(self, event):
        webbrowser.open("http://www.obdtester.com/order")

    def OnHelpAbout(self, event):
        Text = """PyOBD is an automotive OBD2 diagnostic application via ELM237.

(C) 2008-2009 SeCons Ltd.
(C) 2004 Charles Donour Sizemore

http://www.obdtester.com/
http://www.secons.com/

PyOBD is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by the Free Software Foundation; 
either version 2 of the License, or (at your option) any later version.

PyOBD is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
without even the implied warranty of MEHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  
See the GNU General Public License for more details. You should have received a copy of 
the GNU General Public License along with PyOBD; if not, write to 
the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
"""

        #HelpAboutDlg = wx.Dialog(self.frame, id, title="About")

        #box  = wx.BoxSizer(wx.HORIZONTAL)
        #box.Add(wx.StaticText(reconnectPanel,-1,Text,pos=(0,0),size=(200,200)))
        #box.Add(wx.Button(HelpAboutDlg,wx.ID_OK),0)
        #box.Add(wx.Button(HelpAboutDlg,wx.ID_CANCEL),1)

        #HelpAboutDlg.SetSizer(box)
        #HelpAboutDlg.SetAutoLayout(True)
        #sizer.Fit(HelpAboutDlg)
        #HelpAboutDlg.ShowModal()

        self.HelpAboutDlg = wx.MessageDialog(
            self.frame, Text, 'About', wx.OK | wx.ICON_INFORMATION)
        self.HelpAboutDlg.ShowModal()
        self.HelpAboutDlg.Destroy()

    def OnResult(self, event):
        # Sanity check
        if event.data[0] not in self.sensor_map:
            print "Warning: Received data for unsupported sensor %d" % event.data[0]
            return

        self.sensors.SetStringItem(
            self.sensor_map[event.data[0]], event.data[1], event.data[2])

    def OnStatus(self, event):
        # control event
        if len(event.data) == 1:
            if event.data[0] == -1:  # signal, that connection failed
                self.sensor_control_off()
                self.statusBar.SetStatusText("Connection Failed", 0)
            elif event.data[0] == 0:  # disconnected
                self.sensor_control_off()
                self.statusBar.SetStatusText("Disconnected", 0)
            elif event.data[0] == 1:  # connected
                self.sensor_control_on()
                self.statusBar.SetStatusText("Connected", 0)
        else:
            self.status.SetStringItem(
                event.data[0], event.data[1], event.data[2])

    def OnTests(self, event):
        self.OBDTests.SetStringItem(
            event.data[0], event.data[1], event.data[2])

    def OnMonitorData(self, event):
        # data: [id] [8 dwords]
        text_data = event.data[1]
        text_data = text_data.split(' ')
        text_data = text_data[0:9]
        data = [int(i, 16) for i in text_data]

        id = data[0]
        self._monitor_data[id] = data[1:]

        display_text = (event.data[0], "%.3X" % id, " ".join(text_data[1:]))

        # [time, data]
        if id not in self._monitor_map:
            self._monitor_map[id] = self.monitor.GetItemCount()
            self.monitor.Append(display_text)
        else:
            idx = self._monitor_map[id]
            self.monitor.SetStringItem(idx, 0, display_text[0])
            self.monitor.SetStringItem(idx, 2, display_text[2])

        # Ensure it's visible
        # TODO: Add a button to disable this
        self.monitor.EnsureVisible(self.monitor.GetItemCount() - 1)

    def OnDebug(self, event):
        self.TraceDebug(event.data[0], event.data[1])

    def OnDtc(self, event):
        if event.data == 0:  # signal, that DTC was cleared
          self.dtc.DeleteAllItems()
        else:
          self.dtc.Append(event.data)

    def OnDisconnect(self, event):  # disconnect connection to ECU
        self.ThreadControl = 666
        self.sensor_control_off()

    def OpenPort(self, e):
        if self.senprod:  # signal current producers to finish
            self.senprod.stop()
        
        self.statusBar.SetStatusText("Connecting...", 0)
        self.ThreadControl = 0
        self.senprod = self.sensorProducer(
            self, self.COMPORT, self.SERTIMEOUT, self.RECONNATTEMPTS, self.nb)

        # senprod will post a status event when connection succeeded.
        self.senprod.start()

    def GetDTC(self, e):
        self.nb.SetSelection(3)
        self.ThreadControl = 2

    def AddDTC(self, code):
        self.dtc.InsertStringItem(0, "")
        self.dtc.SetStringItem(0, 0, code[0])
        self.dtc.SetStringItem(0, 1, code[1])

    def BeginMonitoring(self, e):
        if self.senprod:
            self._monitor_data = {}
            self.EndMonitorButton.Enable(True)
            self.nb.SetSelection(MyApp.TAB_MONITOR)
            self.ThreadControl = 1

    def EndMonitoring(self, e):
        if self.senprod:
            self.EndMonitorButton.Enable(False)
            self.ThreadControl = 0

    def ClearMonitor(self, e=None):
        self._monitor_data = {}
        self._monitor_map = {}
        self.monitor.DeleteAllItems()

    def SaveMonitor(self, e):
        dlg = wx.FileDialog(self.frame, "Save Data As...", os.getcwd(
        ), "", "*.csv", wx.SAVE | wx.OVERWRITE_PROMPT)
        result = dlg.ShowModal()
        file_path = dlg.GetPath()
        dlg.Destroy()

        if result == wx.ID_OK:
            # TODO: IOError permission denied(write)
            f = open(file_path, "w+")
            if not f:
                self.TraceDebug(3, "Failed to open file %s" % file_path)
                return

            f.write('Time,ID,Data,\n')
            for i in range(0, self.monitor.GetItemCount()):
                time = self.monitor.GetItem(i, 0).GetText()
                id = self.monitor.GetItem(i, 1).GetText()
                data = self.monitor.GetItem(i, 2).GetText()
                f.write('"%s","%s","%s",\n' % (time, id, data))

            f.close()

    def CodeLookup(self, e=None):
        id = 0
        diag = wx.Frame(None, id, title="Diagnostic Trouble Codes")

        tree = wx.TreeCtrl(diag, id, style=wx.TR_HAS_BUTTONS)

        root = tree.AddRoot("Code Reference")
        proot = tree.AppendItem(root, "Powertrain (P) Codes")
        codes = obd_io.pcodes.keys()
        codes.sort()
        group = ""
        for c in codes:
            if c[:3] != group:
                group_root = tree.AppendItem(proot, c[:3] + "XX")
                group = c[:3]
            leaf = tree.AppendItem(group_root, c)
            tree.AppendItem(leaf, obd_io.pcodes[c])

        uroot = tree.AppendItem(root, "Network (U) Codes")
        codes = obd_io.ucodes.keys()
        codes.sort()
        group = ""
        for c in codes:
            if c[:3] != group:
                group_root = tree.AppendItem(uroot, c[:3] + "XX")
                group = c[:3]
            leaf = tree.AppendItem(group_root, c)
            tree.AppendItem(leaf, obd_io.ucodes[c])

        diag.SetSize((400, 500))
        diag.Show(True)

    def QueryClear(self, e):
        id = 0
        diag = wx.Dialog(self.frame, id, title="Clear DTC?")

        sizer = wx.BoxSizer(wx.VERTICAL)
        sizer.Add(wx.StaticText(diag, -1, "Are you sure you wish to"), 0)
        sizer.Add(wx.StaticText(diag, -1, "clear all DTC codes and "), 0)
        sizer.Add(wx.StaticText(diag, -1, "freeze frame data?      "), 0)
        box = wx.BoxSizer(wx.HORIZONTAL)
        box.Add(wx.Button(diag, wx.ID_OK,     "Ok"), 0)
        box.Add(wx.Button(diag, wx.ID_CANCEL, "Cancel"), 0)

        sizer.Add(box, 0)
        diag.SetSizer(sizer)
        diag.SetAutoLayout(True)
        sizer.Fit(diag)
        r = diag.ShowModal()
        if r == wx.ID_OK:
            self.ClearDTC()

    def ClearDTC(self):
        self.ThreadControl = 1
        self.nb.SetSelection(3)

    def Configure(self, e=None):
        id = 0
        diag = wx.Dialog(self.frame, id, title="Configure")
        sizer = wx.BoxSizer(wx.VERTICAL)

        ports = []
        found_ports = True
        ports.extend(scanSerial())
        ports.extend(scanBluetooth())
        if len(ports) == 0:
            ports.append("No ports found")
            found_ports = False

        rb = wx.RadioBox(diag, id, "Choose Serial/Bluetooth Port",
                         choices=ports, style=wx.RA_SPECIFY_COLS,
                         majorDimension=2)
        if found_ports == False:
            rb.Enable(False)

        sizer.Add(rb, 0)

        #timeOut input control
        timeoutPanel = wx.Panel(diag, -1)
        timeoutCtrl = wx.TextCtrl(
            timeoutPanel, -1, '', pos=(140, 0), size=(35, 25))
        timeoutStatic = wx.StaticText(
            timeoutPanel, -1, 'Timeout:', pos=(3, 5), size=(140, 20))
        timeoutCtrl.SetValue(str(self.SERTIMEOUT))

        #reconnect attempt input control
        reconnectPanel = wx.Panel(diag, -1)
        reconnectCtrl = wx.TextCtrl(
            reconnectPanel, -1, '', pos=(140, 0), size=(35, 25))
        reconnectStatic = wx.StaticText(
            reconnectPanel, -1, 'Reconnect attempts:', pos=(3, 5), size=(140, 20))
        reconnectCtrl.SetValue(str(self.RECONNATTEMPTS))

        #web open link button
        self.OpenLinkButton = wx.Button(
            diag, -1, "Click here to order ELM-USB interface", size=(260, 30))
        diag.Bind(wx.EVT_BUTTON, self.OnHelpOrder, self.OpenLinkButton)

        #set actual serial port choice
        if (self.COMPORT != 0) and (self.COMPORT in ports):
          rb.SetSelection(ports.index(self.COMPORT))

        sizer.Add(self.OpenLinkButton)
        sizer.Add(timeoutPanel, 0)
        sizer.Add(reconnectPanel, 0)

        box = wx.BoxSizer(wx.HORIZONTAL)
        box.Add(wx.Button(diag, wx.ID_OK), 0)
        box.Add(wx.Button(diag, wx.ID_CANCEL), 1)

        sizer.Add(box, 0)
        diag.SetSizer(sizer)
        diag.SetAutoLayout(True)
        sizer.Fit(diag)
        r = diag.ShowModal()
        if r == wx.ID_OK:

            #create section
            if self.config.sections() == []:
              self.config.add_section("pyOBD")
            #set and save COMPORT
            self.COMPORT = ports[rb.GetSelection()]
            self.config.set("pyOBD", "COMPORT", self.COMPORT)

            #set and save SERTIMEOUT
            self.SERTIMEOUT = int(timeoutCtrl.GetValue())
            self.config.set("pyOBD", "SERTIMEOUT", self.SERTIMEOUT)
            self.status.SetStringItem(3, 1, self.COMPORT)

            #set and save RECONNATTEMPTS
            self.RECONNATTEMPTS = int(reconnectCtrl.GetValue())
            self.config.set("pyOBD", "RECONNATTEMPTS", self.RECONNATTEMPTS)

            #write configuration to cfg file
            self.config.write(open(self.configfilepath, 'wb'))

    def OnResize(self, e):
        # e.Size.x/y
        self.FRAMESIZE = (e.Size.x, e.Size.y)
        e.Skip()

    def OnExit(self, e=None):
        self.config.set("pyOBD", "WINSIZEX", self.FRAMESIZE[0])
        self.config.set("pyOBD", "WINSIZEY", self.FRAMESIZE[1])
        self.config.write(open(self.configfilepath, 'wb'))

        self.ThreadControl = 666
        import sys
        sys.exit(0)

app = MyApp(0)
app.MainLoop()
